name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: DotNet Bump Versions
      # You may pin to the exact commit or the version.
      # uses: SiqiLu/dotnet-bump-version@e1c7b163e28a598cf7323ab9ccd8915a45c31040
      uses: SiqiLu/dotnet-bump-version@1.0.2
      # with:
        # Version files to bump version. You can use Glob pattern string (like "**/*.csproj") or Glob patterns array json string (like "["**/*.csproj", ".version", "**/*.version.json"]"). Patterns supported by Globby are supported.Leading ! changes the meaning of an include pattern to exclude.
        # version_files: # optional, default is **/*.csproj
        # the github token to push changes
        # github_token: # optional

    - name: Install dependencies
      working-directory: ./src/DateTimeSharp
      run: dotnet restore
    
    - name: Build
      working-directory: ./src/DateTimeSharp
      run: dotnet build --configuration Release --no-restore
    
    - name: Run Unit Tests
      working-directory: ./src/DateTimeSharp
      run: dotnet test --no-restore --verbosity normal

    - name: Pack
      working-directory: ./src/DateTimeSharp
      run: dotnet pack --configuration Release

    - name: Publish
      working-directory: ./src/DateTimeSharp/bin/Release
      run: dotnet nuget push DateTimeSharp.1.0.0.nupkg -s https://nuget.pkg.github.com/merklegroot/index.json --api-key ${{secrets.NUGET_API_KEY}}

